services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile

  guestservice:
    image: ${DOCKER_REGISTRY-}guestservice
    build:
      context: .
      dockerfile: GuestService/Dockerfile

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: guestdb
    ports:
      - "5433:5432"

